basePath: /
definitions:
  main.ShortenRequest:
    properties:
      url:
        example: https://go.dev
        type: string
    type: object
  main.ShortenResponse:
    properties:
      short_url:
        example: http://localhost:8080/abc123
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A fast, vanilla Go URL shortener using Postgres and Redis.
  title: URL Shortener API
  version: "1.0"
paths:
  /{code}:
    get:
      description: Takes a short code in the path and issues a 301 redirect to the
        original URL.
      parameters:
      - description: The 7-character short code
        in: path
        name: code
        required: true
        type: string
      responses:
        "301":
          description: Moved Permanently
        "404":
          description: Not Found
          schema:
            type: string
      summary: Redirect to original URL
  /shorten:
    post:
      consumes:
      - application/json
      description: Takes a long URL, saves it to the database, and returns a short
        Base62 URL.
      parameters:
      - description: The long URL to shorten
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.ShortenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ShortenResponse'
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Shorten a long URL
swagger: "2.0"
